-- database: ./WarehouseData.db3
-- Migrated detail data from Clothing, PPE, and Tools seed records
-- Color and Size default to empty/0.0 where not applicable to the category

INSERT OR IGNORE INTO SKUCatalog (SKUMarker, Category, Type, Color, Size) VALUES
-- Clothing
('CLTH001', 'Workwear',      'Work Shirt',       'Blue',          0.0),
('CLTH002', 'Workwear',      'Cargo Pants',       'Navy',          0.0),
('CLTH003', 'Workwear',      'Coveralls',         'Gray',          0.0),
('CLTH004', 'Hi-Vis Safety', 'Safety Vest',       'Hi-Vis Yellow', 0.0),
('CLTH005', 'Hi-Vis Safety', 'Hi-Vis Jacket',     'Hi-Vis Orange', 0.0),
('CLTH006', 'Hi-Vis Safety', 'Hi-Vis Shirt',      'Hi-Vis Yellow', 0.0),
('CLTH007', 'Cold Weather',  'Thermal Jacket',    'Black',         0.0),
('CLTH008', 'Cold Weather',  'Insulated Pants',   'Black',         0.0),
('CLTH009', 'Cold Weather',  'Fleece Pullover',   'Gray',          0.0),
('CLTH010', 'Workwear',      'Polo Shirt',        'Khaki',         0.0),
('CLTH011', 'Workwear',      'Bib Overalls',      'Blue',          0.0),
('CLTH012', 'Workwear',      'Work Shorts',       'Khaki',         0.0),
('CLTH013', 'General',       'T-Shirt',           'Gray',          0.0),
('CLTH014', 'General',       'Baseball Cap',      'Black',         0.0),
('CLTH015', 'Hi-Vis Safety', 'Safety Vest',       'Hi-Vis Orange', 0.0),
('CLTH016', 'Workwear',      'Denim Jacket',      'Blue',          0.0),
('CLTH017', 'Cold Weather',  'Softshell Jacket',  'Charcoal',      0.0),
('CLTH018', 'Workwear',      'Work Shirt',        'Orange',        0.0),
('CLTH019', 'Workwear',      'Cargo Pants',       'Black',         0.0),
('CLTH020', 'Hi-Vis Safety', 'Hi-Vis Shirt',      'Hi-Vis Orange', 0.0),
('CLTH021', 'General',       'Polo Shirt',        'Navy',          0.0),
('CLTH022', 'Cold Weather',  'Winter Beanie',     'Black',         0.0),
('CLTH023', 'Workwear',      'Coveralls',         'Blue',          0.0),
('CLTH024', 'Hi-Vis Safety', 'Safety Vest',       'Hi-Vis Yellow', 0.0),
('CLTH025', 'Workwear',      'Work Shorts',       'Charcoal',      0.0),
-- PPE
('SPPE001', 'Head Protection',  'Hard Hat',                    '', 0.0),
('SPPE002', 'Head Protection',  'Hard Hat',                    '', 0.0),
('SPPE003', 'Head Protection',  'Bump Cap',                    '', 0.0),
('SPPE004', 'Eye Protection',   'Safety Glasses',              '', 0.0),
('SPPE005', 'Eye Protection',   'Safety Goggles',              '', 0.0),
('SPPE006', 'Eye Protection',   'Face Shield',                 '', 0.0),
('SPPE007', 'Hand Protection',  'Cut-Resistant Gloves',        '',  9.0),
('SPPE008', 'Hand Protection',  'Chemical Resistant Gloves',   '',  9.5),
('SPPE009', 'Hand Protection',  'Leather Work Gloves',         '', 10.0),
('SPPE010', 'Hand Protection',  'Nitrile Disposable Gloves',   '',  8.5),
('SPPE011', 'Foot Protection',  'Steel Toe Work Boots',        '',  9.0),
('SPPE012', 'Foot Protection',  'Steel Toe Work Boots',        '', 10.0),
('SPPE013', 'Foot Protection',  'Metatarsal Guard Boots',      '',  9.5),
('SPPE014', 'Foot Protection',  'Rubber Safety Boots',         '', 11.0),
('SPPE015', 'Respiratory',      'N95 Disposable Respirator',   '', 0.0),
('SPPE016', 'Respiratory',      'Half-Face Respirator',        '', 0.0),
('SPPE017', 'Respiratory',      'Disposable Dust Mask',        '', 0.0),
('SPPE018', 'Hearing',          'Foam Ear Plugs',              '', 0.0),
('SPPE019', 'Hearing',          'Banded Ear Plugs',            '', 0.0),
('SPPE020', 'Hearing',          'Over-Ear Muffs',              '', 0.0),
('SPPE021', 'Head Protection',  'Hard Hat',                    '', 0.0),
('SPPE022', 'Eye Protection',   'Safety Glasses',              '', 0.0),
('SPPE023', 'Hand Protection',  'Cut-Resistant Gloves',        '',  8.0),
('SPPE024', 'Foot Protection',  'Steel Toe Work Boots',        '', 10.5),
('SPPE025', 'Respiratory',      'N95 Disposable Respirator',   '', 0.0),
-- Tools
('PWTL001', 'Power Tools', 'Cordless Drill',          '', 20.0),
('PWTL002', 'Power Tools', 'Circular Saw',            '',  7.25),
('PWTL003', 'Power Tools', 'Angle Grinder',           '',  4.5),
('PWTL004', 'Power Tools', 'Impact Driver',           '', 20.0),
('PWTL005', 'Power Tools', 'Reciprocating Saw',       '', 18.0),
('PWTL006', 'Power Tools', 'Orbital Sander',          '', 20.0),
('PWTL007', 'Power Tools', 'Jigsaw',                  '', 20.0),
('PWTL008', 'Power Tools', 'Rotary Hammer',           '', 20.0),
('PWTL009', 'Power Tools', 'Power Planer',            '', 20.0),
('PWTL010', 'Power Tools', 'Belt Sander',             '', 20.0),
('PWTL011', 'Power Tools', 'Brad Nailer',             '', 18.0),
('PWTL012', 'Power Tools', 'Framing Nailer',          '', 30.0),
('PWTL013', 'Power Tools', 'Air Compressor',          '',  6.0),
('PWTL014', 'Power Tools', 'Table Saw',               '', 10.0),
('PWTL015', 'Power Tools', 'Miter Saw',               '', 12.0),
('PWTL016', 'Power Tools', 'Random Orbit Sander',     '', 20.0),
('PWTL017', 'Power Tools', 'Track Saw',               '',  6.5),
('PWTL018', 'Power Tools', 'Oscillating Multi-Tool',  '', 20.0),
('PWTL019', 'Power Tools', 'Heat Gun',                '',  0.0),
('PWTL020', 'Power Tools', 'Laser Level',             '',  0.0),
('PWTL021', 'Power Tools', 'Cordless Drill',          '', 18.0),
('PWTL022', 'Power Tools', 'Circular Saw',            '',  6.5),
('PWTL023', 'Power Tools', 'Angle Grinder',           '',  5.0),
('PWTL024', 'Power Tools', 'Impact Driver',           '', 18.0),
('PWTL025', 'Power Tools', 'Rotary Hammer',           '', 18.0);
